### PR TITLE
Added customOrder option for the sorted-keys rule

### PR DESCRIPTION
**Pull request by xxsnakerxx**

### CODE REVIEW

**Comment by mayank23** [comment]
Hi @xxsnakerxx ,great idea for a custom sort, however I wonder if we can have the ability to use any custom sort function similar to how we have the ability to use custom message syntax validators (https://github.com/godaddy/eslint-plugin-i18n-json#i18n-jsonvalid-message-syntax) .

 We can have a `sortFunctionPath` option for the `sorted-keys` rule, and can have it accept the path to a file which implements a sort comparator, then we wouldn't need to embed code into the eslint config.

For example, we can do something like this:


```
  rules: {
        'i18n-json/sorted-keys': [
          2,
          {
            sortFunctionPath: path.resolve('./custom-sort.js'),
            indentSpaces: 2
          }
        ],
```

Then in `custom-sort.js`

```
  module.exports = obj => Object.keys(obj)
            .sort((a, b) => a.slice(0, 2)
              .localeCompare(b.slice(0, 2), undefined, { sensitivity: 'base' }))
```

Thoughts?

**Comment by mayank23** [comment]
awesome thanks! will merge this in once I get a security fix out

**Comment by mayank23** [comment]
Merging and will verify and release tomorrow, Thanks!! 😄

**Comment by xxsnakerxx** [comment]
When will this PR be published? I saw the 3.0 release, and it's not there :(

**Comment by mayank23** [comment]
@xxsnakerxx published as v3.1.0 🥳  . Wanted to finalize the readme and add an example project for custom sorting

**Pull request merged**
