### PR TITLE
Update Lodash, remove usage of deprecated per-function Lodash packages, update readme

### LINKED ISSUE #63: Vulnerability in lodash.set
There's a security vulnerability in the lodash.set package that's used by this project, see: https://github.com/advisories/GHSA-p6mc-m468-83gw

Seems there's no newer version of lodash.set specifically, but apparently the lodash main project provides all the subproject functionality and using the per-function packages is deprecated: https://github.com/lodash/lodash/issues/5882

### PR DESCRIPTION
**Pull request by laveez**
- Update Lodash
- Remove usage of deprecated per-function Lodash packages
- Update readme with instructions on how to use this package with npm `>= 9.0.0` as described in #62

Closes #63

### CODE REVIEW

**Comment by Crare** [comment]
3 weeks ago... is this still waiting for something?

**Comment by laveez** [comment]
@Crare well, it's waiting for someone at the [@godaddy](https://github.com/godaddy) to approve/merge it. I have no write access. Wouldn't get hopes up though, since this repository has been stale for a while 🫤 

In the meantime, I've been using my own [fork](https://github.com/laveez/eslint-plugin-i18n-json) 🤷🏻

**Review by rmarkins-godaddy — APPROVED** [review]

**Comment by mpawar-ep-910** [comment]
@laveez Hi We are using your fork package and i'ts working fine. thanks

**Comment by laveez** [comment]
This was merged and therefore fixed in this original repo too, use the original! @mpawar-ep-910

**Comment by mpawar-ep-910** [comment]
yes i just saw that thank you @laveez  reverted.

**Pull request merged**
