### PR TITLE
Fix 'valid-message-syntax' rule with `icu` syntax

### PR DESCRIPTION
**Pull request by darkyndy**
See issue https://github.com/godaddy/eslint-plugin-i18n-json/issues/24 

@mayank23 can you please review?

### CODE REVIEW

**Comment by mayank23** [comment]
Thanks for the PR, will get this published this evening

**Comment by darkyndy** [comment]
Thanks @mayank23 for reviewing. Can you also publish it? :)

**Comment by mayank23** [comment]
Yes can do tomorrow :)

**Comment by mayank23** [comment]
@darkyndy published! v2.4.2. Thanks a lot for the help 😄

**Pull request merged**
